apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend.yaml
  - frontend.yaml
  - secrets.yaml

namespace: patchflow

images:
  - name: ghcr.io/lucieran-raven/patchflow/backend
    newTag: latest
  - name: ghcr.io/lucieran-raven/patchflow/frontend
    newTag: latest
